name: Ruby on Rails CI

on:
  push:
    branches-ignore:
      - stable

jobs:
  rails-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - 3.0.3

    env:
      RAILS_ENV: test
      PROJECT_DATABASE_HOST: db
      PROJECT_DATABASE_PORT: 3306:3306
      PROJECT_DATABASE_DBNAME: myapp_development
      PROJECT_DATABASE_USERNAME: root
      PROJECT_DATABASE_PASSWORD: root
      TZ: Asia/Tokyo

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: ${{ env.PROJECT_DATABASE_DBNAME }}
          MYSQL_USER: ${{ env.PROJECT_DATABASE_USERNAME }}
          MYSQL_PASSWORD: ${{ env.PROJECT_DATABASE_PASSWORD }}
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          TZ: Asia/Tokyo
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3306:3306
    steps:    
      - name: Checkout
        uses: actions/checkout@v2

      # Resolve gems dependencies
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      # Pre-test setting
      - name: Setup database
        run: bundle exec rake db:create db:schema:load

      # Executing lint
      - name: Run linters
        run: bundle exec rubocop

      # Executing test
      - name: Run tests
        run: bundle exec rspec

      - name: Set up MySQL
        run: | 
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
  
  slack-notify:
    runs-on: ubuntu-latest
    needs:
      - rails-test
    if: always()
    steps:
      # run this action to get workflow conclusion
      # You can get conclusion via env (env.WORKFLOW_CONCLUSION)
      - name: Receive job statuses
        uses: technote-space/workflow-conclusion-action@v2
      - name: Slack Notification
        uses: weseek/ghaction-slack-notification@master
        with:
          type: ${{ env.WORKFLOW_CONCLUSION }}
          job_name: '*Test*'
          channel: '#channel_name'
          isCompactMode: true
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
